# To use:
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate scipy-dev
#
# Also used to build the `scipy-dev` Docker image via GitHub Actions
name: scipy-meson
channels:
  - conda-forge
dependencies:
  - python
  - cython
  - compilers
  - ninja
  - numpy
  - openblas
  - pkg-config  # note: not available on Windows
  - libblas=*=*openblas  # helps avoid pulling in MKL
  - pybind11
  - pythran>=0.9.12
  - conda-build  # to allow `conda develop .`
  # For testing and benchmarking
  - pytest
  - pytest-cov
  - pytest-xdist
  - asv
  # For type annotations
  - mypy
  - typing_extensions
  # For building docs
  - sphinx
  - numpydoc=1.1.0
  - ipython
  - matplotlib
  - pydata-sphinx-theme
  - sphinx-panels
  # For linting
  - flake8
  # Some optional test dependencies
  - mpmath
  - gmpy2
  - pip
  - pip:
    - meson==0.60.0rc1
