#!/usr/bin/env python3
"""
Code generator that produces Cython `def` wrappers around the existing
cython_blas/cython_lapack `cdef` functions.

These generated wrappers replace the f2py-generated _fblas/_flapack modules
by providing equivalent Python-callable interfaces with:
- NumPy array input/output
- Automatic Fortran-order conversion and dtype casting
- Dimension inference from array shapes
- Input validation (checks)
- Copy/overwrite semantics
- Workspace allocation for hidden work arrays

Usage::

    python _generate_pywrappers.py -o <outdir> [--ilp64]

This reads the .pyf.src files and cython_*_signatures.txt to generate:
- _pyblas.pyx / _pyblas.pxd  (or _pyblas_64 for ILP64)
- _pylapack.pyx / _pylapack.pxd  (or _pylapack_64 for ILP64)
"""

import argparse
import os
import re
import textwrap

# We use importlib to avoid triggering scipy's __init__.py
import importlib.util


def _import_module_from_file(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


BASE_DIR = os.path.abspath(os.path.dirname(__file__))

# Import _extract_balanced_parens from _pyf_parser without triggering scipy import
_pyf_parser = _import_module_from_file(
    '_pyf_parser', os.path.join(BASE_DIR, '_pyf_parser.py')
)
_extract_balanced_parens = _pyf_parser._extract_balanced_parens

# Map f2py Fortran types to numpy dtype strings and C types
FTYPE_TO_NUMPY = {
    'real': 'np.float32',
    'double precision': 'np.float64',
    'complex': 'np.complex64',
    'double complex': 'np.complex128',
    'integer': 'np.intc',  # will be overridden for blas_int
}

FTYPE_TO_CTYPE = {
    'real': 'float',
    'double precision': 'double',
    'complex': 'float complex',
    'double complex': 'double complex',
}

# Map ftype to single-char prefix
FTYPE_TO_PREFIX = {
    'real': 's',
    'double precision': 'd',
    'complex': 'c',
    'double complex': 'z',
}

def _is_simple_literal(s):
    """Check if a string is a simple compile-time literal (int, float, tuple)."""
    s = s.strip()
    # Integer
    if re.match(r'^-?\d+$', s):
        return True
    # Float
    if re.match(r'^-?\d+\.?\d*$', s):
        return True
    # Complex tuple like (0.0,0.0)
    if re.match(r'^\([\d.,\s]+\)$', s):
        return True
    return False


COMMENT_HEADER = """\
# This file was generated by _generate_pywrappers.py.
# Do not edit this file directly.
"""


def _get_python_args(routine):
    """Get the list of Python-visible arguments for a routine.

    Hidden args (intent(hide)) and cache args are excluded.
    Arguments are returned in a sensible order: required args first,
    then optional args. Required arrays, then required scalars, then
    optional keyword args.
    """
    required = []
    optional = []
    for aname in routine['arg_names']:
        ainfo = routine['args'].get(aname, {})
        intents = ainfo.get('intents', [])
        if 'hide' in intents:
            continue
        if 'cache' in intents:
            continue

        # Pure output scalars (intent(out) without intent(in)) are not
        # passed by the user - they're allocated internally and returned.
        # But output ARRAYS may be optionally passed for in-place operation.
        if 'out' in intents and 'in' not in intents and not _is_array_arg(ainfo):
            continue

        is_opt = ainfo.get('optional', False)
        has_default = 'default' in ainfo
        # Output-only arrays are optional (user can let us allocate)
        if 'out' in intents and 'in' not in intents and _is_array_arg(ainfo):
            optional.append(aname)
        elif is_opt or has_default:
            optional.append(aname)
        else:
            required.append(aname)

    # Also add any args that are not in arg_names but have 'out' intent
    for aname, ainfo in routine['args'].items():
        if aname not in routine['arg_names']:
            intents = ainfo.get('intents', [])
            if 'out' in intents and aname not in required and aname not in optional:
                # Pure output args that aren't in the signature are
                # typically allocated internally, not passed by user
                pass

    return required + optional


def _get_hidden_args(routine):
    """Get args with intent(hide), topologically sorted by dependencies.

    Hidden args often depend on each other (e.g., m depends on lda which
    depends on shape(a,0)). We sort them so that each arg is computed
    after its dependencies.
    """
    hidden = []
    for aname in routine['arg_names']:
        ainfo = routine['args'].get(aname, {})
        intents = ainfo.get('intents', [])
        if 'hide' in intents or 'cache' in intents:
            hidden.append(aname)

    # Topological sort based on depend() chains
    # Only consider dependencies between hidden args
    hidden_set = set(hidden)
    sorted_hidden = []
    visited = set()

    def visit(name):
        if name in visited:
            return
        visited.add(name)
        ainfo = routine['args'].get(name, {})
        for dep in ainfo.get('depend', []):
            if dep in hidden_set:
                visit(dep)
        sorted_hidden.append(name)

    for name in hidden:
        visit(name)

    return sorted_hidden


def _get_output_args(routine):
    """Get args that should be returned (intent out or in,out)."""
    outputs = []
    for aname, ainfo in routine['args'].items():
        intents = ainfo.get('intents', [])
        if 'out' in intents:
            outputs.append(aname)
    return outputs


def _is_array_arg(ainfo):
    """Check if an argument is an array (has dimension)."""
    return ainfo.get('dimension') is not None


def _translate_f2py_expr(expr, routine_args):
    """Translate an f2py expression to Python.

    Handles common patterns like:
    - shape(a, 0) -> a.shape[0]
    - len(x) -> x.shape[0]  (for 1D arrays)
    - MAX(a, b) -> max(a, b)
    - C ternary: (cond ? val1 : val2) -> (val1 if cond else val2)
    """
    if expr is None:
        return None

    result = expr.strip()

    # shape(var, idx) -> var.shape[idx]
    result = re.sub(r'shape\((\w+)\s*,\s*(\d+)\)', r'\1.shape[\2]', result)

    # len(var) -> var.shape[0]
    result = re.sub(r'len\((\w+)\)', r'\1.shape[0]', result)

    # MAX(a, b) -> max(a, b) (case insensitive)
    result = re.sub(r'MAX\(', 'max(', result)
    result = re.sub(r'MIN\(', 'min(', result)

    # abs() is already Python-compatible

    # C ternary expressions: (cond ? a : b) -> (a if cond else b)
    # This is complex due to nesting; handle simple cases
    result = _translate_ternary(result)

    # C logical operators
    result = result.replace('&&', ' and ')
    result = result.replace('||', ' or ')

    return result


def _translate_ternary(expr):
    """Translate C ternary (cond ? a : b) to Python (a if cond else b).

    Handles nested ternaries.
    """
    # Simple non-nested case first
    # Pattern: (cond?val1:val2) where cond, val1, val2 don't contain ?:
    while '?' in expr:
        # Find innermost ternary (no nested ? inside)
        m = re.search(r'\(([^?()]*)\?([^?():]*):([^?()]*)\)', expr)
        if m:
            cond = m.group(1).strip()
            val1 = m.group(2).strip()
            val2 = m.group(3).strip()
            replacement = f'({val1} if {cond} else {val2})'
            expr = expr[:m.start()] + replacement + expr[m.end():]
        else:
            # Try without outer parens
            m = re.search(r'([^?(]*)\?([^?:]*):([^?]*)', expr)
            if m:
                cond = m.group(1).strip()
                val1 = m.group(2).strip()
                val2 = m.group(3).strip()
                replacement = f'({val1} if {cond} else {val2})'
                expr = expr[:m.start()] + replacement + expr[m.end():]
            else:
                break
    return expr


def _get_numpy_dtype(ftype):
    """Get numpy dtype for a Fortran type."""
    return FTYPE_TO_NUMPY.get(ftype, 'np.float64')


def _get_overwrite_param_name(aname):
    """Get the overwrite_X parameter name for a copy intent arg."""
    return f'overwrite_{aname}'


def _generate_wrapper_function(routine, lib_module_name):
    """Generate a Cython def wrapper function for one routine.

    Parameters
    ----------
    routine : dict
        Parsed routine specification from _pyf_parser.
    lib_module_name : str
        'cython_blas' or 'cython_lapack'

    Returns
    -------
    code : str
        Cython source code for the wrapper function.
    """
    name = routine['name']
    is_function = routine['type'] == 'function'
    py_args = _get_python_args(routine)
    hidden_args = _get_hidden_args(routine)
    output_args = _get_output_args(routine)

    # Determine the primary data type from first array arg or first typed arg
    primary_ftype = None
    for aname in routine['arg_names']:
        ainfo = routine['args'].get(aname, {})
        ft = ainfo.get('ftype')
        if ft and ft != 'integer':
            primary_ftype = ft
            break
    if primary_ftype is None:
        primary_ftype = 'double precision'

    numpy_dtype = _get_numpy_dtype(primary_ftype)

    lines = []

    # Build function signature
    # Defaults that reference other args can't be in the signature -
    # they must be computed in the function body using sentinel values.
    sig_parts = []
    body_defaults = []  # (argname, expr) for defaults computed in body

    for aname in py_args:
        ainfo = routine['args'].get(aname, {})
        intents = ainfo.get('intents', [])
        default = ainfo.get('default')
        is_optional = ainfo.get('optional', False)

        if _is_array_arg(ainfo):
            # Array args: accept as object, convert later
            if is_optional or ('out' in intents and 'in' not in intents):
                sig_parts.append(f'{aname}=None')
            else:
                sig_parts.append(aname)
        elif ainfo.get('ftype') == 'integer':
            if is_optional and default is not None:
                # Check if default is a simple literal
                if _is_simple_literal(default):
                    sig_parts.append(f'int {aname}={default}')
                else:
                    # Computed default - use sentinel
                    sig_parts.append(f'int {aname}=-1')
                    py_expr = _translate_f2py_expr(default, routine['args'])
                    body_defaults.append((aname, py_expr))
            else:
                sig_parts.append(f'int {aname}')
        else:
            # Scalar of the routine's type
            if is_optional and default is not None:
                if _is_simple_literal(default):
                    sig_parts.append(f'{aname}={default}')
                else:
                    sig_parts.append(f'{aname}=None')
                    py_expr = _translate_f2py_expr(default, routine['args'])
                    body_defaults.append((aname, py_expr))
            else:
                sig_parts.append(aname)

    # Add overwrite_ parameters for intent(in,out,copy) arrays
    for aname in py_args:
        ainfo = routine['args'].get(aname, {})
        intents = ainfo.get('intents', [])
        if 'copy' in intents and 'in' in intents and 'out' in intents:
            ow_name = _get_overwrite_param_name(aname)
            sig_parts.append(f'int {ow_name}=0')
        elif 'in' in intents and 'out' in intents and _is_array_arg(ainfo):
            # in,out without copy - overwrite by default
            ow_name = _get_overwrite_param_name(aname)
            sig_parts.append(f'int {ow_name}=0')

    sig = ', '.join(sig_parts)
    lines.append(f'def {name}({sig}):')

    # Docstring (minimal)
    lines.append(f'    """Wrapper for ``{name}``."""')

    # --- Variable declarations ---
    lines.append('    cdef:')

    # Declare blas_int variables for hidden integer args
    int_vars = []
    for aname in hidden_args:
        ainfo = routine['args'].get(aname, {})
        if ainfo.get('ftype') == 'integer':
            int_vars.append(aname)
    if int_vars:
        lines.append(f'        blas_int {", ".join(int_vars)}')

    # Declare output scalar variables (intent(out) without intent(in))
    for aname in routine['arg_names']:
        ainfo = routine['args'].get(aname, {})
        intents = ainfo.get('intents', [])
        if 'out' in intents and 'in' not in intents and not _is_array_arg(ainfo):
            ftype = ainfo.get('ftype', 'integer')
            if ftype == 'integer':
                lines.append(f'        blas_int {aname}')
            else:
                ctype = FTYPE_TO_CTYPE.get(ftype, 'double')
                lines.append(f'        {ctype} {aname}')

    # Declare function return variable if needed
    if is_function and routine.get('result_name'):
        rname = routine['result_name']
        # Determine return type: check return_type, then look in args for
        # the result variable or function name, then fall back to primary type
        rtype = routine.get('return_type')
        if not rtype:
            # Check if result name or function name has a type declaration
            for vname in [rname, routine['name']]:
                if vname in routine['args'] and 'ftype' in routine['args'][vname]:
                    rtype = routine['args'][vname]['ftype']
                    break
        if not rtype:
            rtype = primary_ftype
        ctype = FTYPE_TO_CTYPE.get(rtype, 'double')
        lines.append(f'        {ctype} {rname}')

    # --- Computed defaults (for args whose defaults reference other args) ---
    if body_defaults:
        lines.append('')
        for aname, expr in body_defaults:
            ainfo = routine['args'].get(aname, {})
            if ainfo.get('ftype') == 'integer':
                lines.append(f'    if {aname} == -1:')
                lines.append(f'        {aname} = {expr}')
            else:
                lines.append(f'    if {aname} is None:')
                lines.append(f'        {aname} = {expr}')

    # --- Input validation and array conversion ---
    lines.append('')

    # Process array arguments: convert to Fortran-contiguous, correct dtype
    for aname in py_args:
        ainfo = routine['args'].get(aname, {})
        if not _is_array_arg(ainfo):
            continue

        intents = ainfo.get('intents', [])
        ftype = ainfo.get('ftype', primary_ftype)
        dt = _get_numpy_dtype(ftype)
        is_optional = ainfo.get('optional', False)

        if 'copy' in intents and 'in' in intents and 'out' in intents:
            # intent(in,out,copy) - copy unless overwrite
            ow_name = _get_overwrite_param_name(aname)
            if is_optional:
                lines.append(f'    if {aname} is not None:')
                lines.append(f'        if not {ow_name}:')
                lines.append(f'            {aname} = np.array({aname}, dtype={dt}, order="F", copy=True)')
                lines.append(f'        else:')
                lines.append(f'            {aname} = np.asfortranarray({aname}, dtype={dt})')
            else:
                lines.append(f'    if not {ow_name}:')
                lines.append(f'        {aname} = np.array({aname}, dtype={dt}, order="F", copy=True)')
                lines.append(f'    else:')
                lines.append(f'        {aname} = np.asfortranarray({aname}, dtype={dt})')
        elif 'in' in intents and 'out' in intents:
            # intent(in,out) without copy - still handle overwrite
            ow_name = _get_overwrite_param_name(aname)
            lines.append(f'    if not {ow_name}:')
            lines.append(f'        {aname} = np.array({aname}, dtype={dt}, order="F", copy=True)')
            lines.append(f'    else:')
            lines.append(f'        {aname} = np.asfortranarray({aname}, dtype={dt})')
        elif 'in' in intents and 'copy' in intents:
            # intent(in,copy) - always copy
            lines.append(f'    {aname} = np.array({aname}, dtype={dt}, order="F", copy=True)')
        elif 'in' in intents:
            # intent(in) only - just ensure correct dtype and order
            lines.append(f'    {aname} = np.asfortranarray({aname}, dtype={dt})')
        elif 'out' in intents:
            # intent(out) only - will be allocated below
            pass

    # --- Compute hidden args ---
    lines.append('')
    for aname in hidden_args:
        ainfo = routine['args'].get(aname, {})
        default = ainfo.get('default')
        if default is not None:
            py_expr = _translate_f2py_expr(default, routine['args'])
            if ainfo.get('ftype') == 'integer':
                lines.append(f'    {aname} = {py_expr}')
            else:
                lines.append(f'    {aname} = {py_expr}')

    # --- Allocate output-only arrays ---
    lines.append('')
    for aname in py_args:
        ainfo = routine['args'].get(aname, {})
        intents = ainfo.get('intents', [])
        dim = ainfo.get('dimension')
        ftype = ainfo.get('ftype', primary_ftype)
        dt = _get_numpy_dtype(ftype)

        if 'out' in intents and 'in' not in intents and dim:
            # Pure output array - allocate
            shape = _translate_dimension_to_shape(dim)
            lines.append(f'    {aname} = np.empty({shape}, dtype={dt}, order="F")')
        elif 'out' in intents and 'in' in intents and dim:
            is_optional = ainfo.get('optional', False)
            if is_optional:
                # Optional in,out array - allocate if not provided
                shape = _translate_dimension_to_shape(dim)
                lines.append(f'    if {aname} is None:')
                lines.append(f'        {aname} = np.zeros({shape}, dtype={dt}, order="F")')

    # --- Allocate hidden workspace arrays ---
    for aname in hidden_args:
        ainfo = routine['args'].get(aname, {})
        dim = ainfo.get('dimension')
        ftype = ainfo.get('ftype')
        if dim and ftype and ftype != 'integer':
            dt = _get_numpy_dtype(ftype)
            shape = _translate_dimension_to_shape(dim)
            lines.append(f'    cdef np.ndarray {aname}_arr = np.empty({shape}, dtype={dt}, order="F")')
        elif dim and ftype == 'integer':
            shape = _translate_dimension_to_shape(dim)
            lines.append(f'    cdef np.ndarray {aname}_arr = np.empty({shape}, dtype=np.intc, order="F")')

    # --- Call the low-level cdef function ---
    lines.append('')
    call_args = _build_call_args(routine, lib_module_name)
    if is_function and routine.get('result_name'):
        result_var = routine['result_name']
        lines.append(f'    {result_var} = {lib_module_name}.{name}({call_args})')
    else:
        lines.append(f'    {lib_module_name}.{name}({call_args})')

    # --- Build return value ---
    lines.append('')
    return_parts = _build_return(routine)
    if return_parts:
        lines.append(f'    return {", ".join(return_parts)}')

    return '\n'.join(lines) + '\n'


def _translate_dimension_to_shape(dim):
    """Translate an f2py dimension string to a Python shape tuple.

    '(m,n)' -> '(m, n)'
    '*' -> '(n,)'  (handled separately)
    'n' -> '(n,)'
    'lda, n' -> '(lda, n)'
    """
    dim = dim.strip()
    if dim == '*':
        return None  # 1D, size determined from input

    # Translate f2py expressions
    dim = _translate_f2py_expr(dim, {})

    parts = [p.strip() for p in dim.split(',')]
    if len(parts) == 1:
        return f'({parts[0]},)'
    else:
        return f'({", ".join(parts)})'


def _build_call_args(routine, lib_module_name):
    """Build the argument string for calling the cython_blas/lapack cdef function.

    The cdef functions take pointers: scalars by &, arrays by &arr[0] or &arr[0,0].
    """
    cs = routine.get('callstatement')
    if cs:
        return _translate_callstatement_args(routine)

    # No callstatement - build from callprotoargument and arg_names.
    # The cython_blas/lapack cdef functions follow the Fortran calling
    # convention: all args passed by pointer.
    args = []
    for aname in routine['arg_names']:
        ainfo = routine['args'].get(aname, {})
        if _is_array_arg(ainfo):
            args.append(f'<{_ctype_ptr(ainfo)}>np.PyArray_DATA({aname})')
        else:
            args.append(f'&{aname}')
    return ', '.join(args)


def _ctype_ptr(ainfo):
    """Get C pointer type for an arg."""
    ftype = ainfo.get('ftype', 'double precision')
    ctype = FTYPE_TO_CTYPE.get(ftype, 'double')
    return f'{ctype} *'


def _parse_callstatement(routine):
    """Parse the callstatement into structured components.

    Returns a dict with:
    - 'pre_call': list of C statements before the function call
    - 'call_args': list of raw argument expressions
    - 'post_call': list of C statements after the function call
    - 'return_assign': variable name if the call returns a value, else None
    """
    cs = routine['callstatement']
    if cs is None:
        return None

    result = {
        'pre_call': [],
        'call_args': [],
        'post_call': [],
        'return_assign': None,
    }

    # Handle compound statements: {stmts; (*f2py_func)(...); stmts}
    if cs.startswith('{'):
        # Split into statements
        inner = cs[1:].rstrip('}').strip()
        stmts = _split_c_statements(inner)
        found_call = False
        for stmt in stmts:
            stmt = stmt.strip()
            if '(*f2py_func)' in stmt:
                found_call = True
                _parse_func_call(stmt, result)
            elif not found_call:
                result['pre_call'].append(stmt)
            else:
                result['post_call'].append(stmt)
    else:
        _parse_func_call(cs, result)

    return result


def _split_c_statements(s):
    """Split C code by semicolons, respecting braces and strings."""
    stmts = []
    depth = 0
    in_str = False
    current = []
    for ch in s:
        if ch == '"':
            in_str = not in_str
            current.append(ch)
        elif ch == '{' and not in_str:
            depth += 1
            current.append(ch)
        elif ch == '}' and not in_str:
            depth -= 1
            current.append(ch)
        elif ch == ';' and depth == 0 and not in_str:
            stmts.append(''.join(current))
            current = []
        else:
            current.append(ch)
    if current:
        stmts.append(''.join(current))
    return [s for s in stmts if s.strip()]


def _parse_func_call(stmt, result):
    """Parse a statement containing (*f2py_func)(args...) into result dict."""
    # Check for return value assignment
    assign_match = re.match(r'(\w+)\s*=\s*\(\*f2py_func\)', stmt)
    if assign_match:
        result['return_assign'] = assign_match.group(1)

    # Extract arguments from (*f2py_func)(...)
    # Find the opening paren after (*f2py_func)
    idx = stmt.find('(*f2py_func)')
    if idx == -1:
        return
    idx += len('(*f2py_func)')
    # Find the argument list
    if idx < len(stmt) and stmt[idx] == '(':
        args_str, _ = _extract_balanced_parens(stmt, idx)
        result['call_args'] = _split_respecting_parens_and_quotes(args_str)
    else:
        result['call_args'] = []


def _translate_callstatement_args(routine):
    """Translate callstatement arguments to Cython function call arguments."""
    parsed = _parse_callstatement(routine)
    if parsed is None:
        # No callstatement - build args from arg_names order
        args = []
        for aname in routine['arg_names']:
            ainfo = routine['args'].get(aname, {})
            if _is_array_arg(ainfo):
                args.append(f'<{_ctype_ptr(ainfo)}>np.PyArray_DATA({aname})')
            else:
                args.append(f'&{aname}')
        return ', '.join(args)

    translated = []
    for raw_arg in parsed['call_args']:
        raw_arg = raw_arg.strip()
        translated.append(_translate_single_call_arg(raw_arg, routine))

    return ', '.join(translated)


def _split_respecting_parens_and_quotes(s):
    """Split by comma, respecting parentheses and quoted strings."""
    parts = []
    depth = 0
    in_quote = False
    current = []
    for ch in s:
        if ch == '"' and not in_quote:
            in_quote = True
            current.append(ch)
        elif ch == '"' and in_quote:
            in_quote = False
            current.append(ch)
        elif ch == '(' and not in_quote:
            depth += 1
            current.append(ch)
        elif ch == ')' and not in_quote:
            depth -= 1
            current.append(ch)
        elif ch == ',' and depth == 0 and not in_quote:
            parts.append(''.join(current))
            current = []
        else:
            current.append(ch)
    parts.append(''.join(current))
    return parts


def _translate_single_call_arg(arg, routine):
    """Translate a single callstatement argument to Cython.

    Returns a tuple (setup_lines, call_expr) where:
    - setup_lines: list of lines to add before the call (e.g., char variable setup)
    - call_expr: the expression to use in the function call

    Common patterns:
    - &var -> &var (scalar by reference)
    - var -> <type *>np.PyArray_DATA(var) (array pointer)
    - x+offx -> <type *>np.PyArray_DATA(x) + offx (array with offset)
    - &"CHARS"[idx] -> char pointer via string lookup
    - (cond?"X":"Y") -> char variable via conditional
    """
    arg = arg.strip()

    # String indexing: &"CHARS"[var]
    str_idx_match = re.match(r'&"([^"]+)"\[(\w+)\]', arg)
    if str_idx_match:
        chars = str_idx_match.group(1)
        var = str_idx_match.group(2)
        return f'&"{chars}"[{var}]'

    # Ternary char mapping: (cond?"X":"Y") or nested
    if '?' in arg and '"' in arg:
        return _translate_char_ternary(arg, routine)

    # &var - scalar by reference
    if arg.startswith('&'):
        varname = arg[1:]
        ainfo = routine['args'].get(varname, {})
        if _is_array_arg(ainfo):
            return f'<{_ctype_ptr(ainfo)}>np.PyArray_DATA({varname})'
        else:
            return f'&{varname}'

    # array+offset: var+off
    plus_match = re.match(r'(\w+)\+(\w+)', arg)
    if plus_match:
        varname = plus_match.group(1)
        offset = plus_match.group(2)
        ainfo = routine['args'].get(varname, {})
        if _is_array_arg(ainfo):
            return f'<{_ctype_ptr(ainfo)}>np.PyArray_DATA({varname}) + {offset}'
        else:
            return f'{varname} + {offset}'

    # Plain variable name
    ainfo = routine['args'].get(arg, {})
    if _is_array_arg(ainfo):
        return f'<{_ctype_ptr(ainfo)}>np.PyArray_DATA({arg})'
    elif arg in routine['args']:
        return f'&{arg}'
    else:
        # Could be a literal or expression
        return arg


def _translate_char_ternary(expr, routine):
    """Translate a C char* ternary to Cython.

    Handles various patterns of integer-to-char mappings used in f2py
    callstatements. Returns a Cython expression that produces a char*.

    Patterns handled:
    - (var?"X":"Y") -> &"YX"[var]
    - (var?(var==2?"C":"T"):"N") -> &"NTC"[var]
    - (var>0?(var==1?"T":"C"):"N") -> &"NTC"[var]
    - (a?(b?"X":"Y"):"Z") -> nested boolean
    - (a?(b?"X":"Y"):(c?"W":"Z")) -> double nested boolean
    """
    expr = expr.strip()

    # Pattern 1: Three-way via ==: (var?(var==2?"C":"T"):"N")
    m = re.match(
        r'\((\w+)\?\((\w+)==(\d+)\?"(.)":"(.)"\):"(.)"\)',
        expr
    )
    if m:
        var = m.group(1)
        val = int(m.group(3))
        char_eq = m.group(4)
        char_neq = m.group(5)
        char_false = m.group(6)
        if val == 2:
            lookup = char_false + char_neq + char_eq
            return f'&"{lookup}"[{var}]'

    # Pattern 2: Three-way via >0 and ==1: (var>0?(var==1?"T":"C"):"N")
    m = re.match(
        r'\((\w+)>0\?\((\w+)==(\d+)\?"(.)":"(.)"\):"(.)"\)',
        expr
    )
    if m:
        var = m.group(1)
        val = int(m.group(3))
        char_eq = m.group(4)
        char_neq = m.group(5)
        char_false = m.group(6)
        if val == 1:
            lookup = char_false + char_eq + char_neq
            return f'&"{lookup}"[{var}]'

    # Pattern 3: Nested boolean: (a?(b?"X":"Y"):"Z")
    m = re.match(
        r'\((\w+)\?\((\w+)\?"(.)":"(.)"\):"(.)"\)',
        expr
    )
    if m:
        var_a = m.group(1)
        var_b = m.group(2)
        char_bt = m.group(3)  # b true
        char_bf = m.group(4)  # b false
        char_af = m.group(5)  # a false
        return (f'(&"{char_bf}{char_bt}"[{var_b}] if {var_a} '
                f'else &"{char_af}"[0])')

    # Pattern 4: Double nested: (a?(b?"X":"Y"):(c?"W":"Z"))
    m = re.match(
        r'\((\w+)\?\((\w+)\?"(.)":"(.)"\):\((\w+)\?"(.)":"(.)"\)\)',
        expr
    )
    if m:
        var_a = m.group(1)
        var_b = m.group(2)
        char_bt = m.group(3)
        char_bf = m.group(4)
        var_c = m.group(5)
        char_ct = m.group(6)
        char_cf = m.group(7)
        return (f'(&"{char_bf}{char_bt}"[{var_b}] if {var_a} '
                f'else &"{char_cf}{char_ct}"[{var_c}])')

    # Pattern 5: Simple boolean: (var?"X":"Y")
    m = re.match(r'\((\w+)\?"(.)":"(.)"\)', expr)
    if m:
        var = m.group(1)
        char_true = m.group(2)
        char_false = m.group(3)
        return f'&"{char_false}{char_true}"[{var}]'

    # Fallback: leave as C comment for manual fix
    return f'/* FIXME char ternary: {expr} */'


def _build_return(routine):
    """Build the return value expression for a routine.

    Returns list of (variable_name, return_name) tuples.
    variable_name is the actual variable in scope; return_name is
    what f2py would name it in the return tuple (via out=X).
    """
    is_function = routine['type'] == 'function'
    output_args = _get_output_args(routine)

    return_parts = []
    seen = set()

    # For functions, the return value comes first
    if is_function and routine.get('result_name'):
        rn = routine['result_name']
        return_parts.append(rn)
        seen.add(rn)

    # Then output arrays/scalars
    for aname in output_args:
        ainfo = routine['args'].get(aname, {})
        out_name = ainfo.get('out_name', aname)
        # The actual variable is `aname`, returned as `out_name`
        if out_name not in seen:
            return_parts.append(aname)
            seen.add(out_name)

    return return_parts


def generate_blas_pyx(routines, ilp64=False):
    """Generate the _pyblas.pyx content."""
    lines = [COMMENT_HEADER]
    lines.append('# cython: boundscheck = False')
    lines.append('# cython: wraparound = False')
    lines.append('# cython: cdivision = True')
    lines.append('')
    lines.append('import numpy as np')
    lines.append('cimport numpy as np')
    lines.append('from scipy.linalg cimport cython_blas')
    lines.append('from scipy.linalg.cython_blas cimport blas_int')
    lines.append('')
    lines.append('np.import_array()')
    lines.append('')
    lines.append('')

    for routine in routines:
        code = _generate_wrapper_function(routine, 'cython_blas')
        lines.append(code)
        lines.append('')

    return '\n'.join(lines)


def generate_lapack_pyx(routines, ilp64=False):
    """Generate the _pylapack.pyx content."""
    lines = [COMMENT_HEADER]
    lines.append('# cython: boundscheck = False')
    lines.append('# cython: wraparound = False')
    lines.append('# cython: cdivision = True')
    lines.append('')
    lines.append('import numpy as np')
    lines.append('cimport numpy as np')
    lines.append('from scipy.linalg cimport cython_lapack')
    lines.append('from scipy.linalg.cython_lapack cimport blas_int')
    lines.append('')
    lines.append('np.import_array()')
    lines.append('')
    lines.append('')

    for routine in routines:
        code = _generate_wrapper_function(routine, 'cython_lapack')
        lines.append(code)
        lines.append('')

    return '\n'.join(lines)


def main():
    parser_module = _import_module_from_file(
        '_pyf_parser',
        os.path.join(BASE_DIR, '_pyf_parser.py')
    )

    ap = argparse.ArgumentParser(description='Generate Python BLAS/LAPACK wrappers')
    ap.add_argument('-o', '--outdir', required=True,
                    help='Output directory')
    ap.add_argument('--ilp64', action='store_true',
                    help='Generate ILP64 wrappers')
    ap.add_argument('--blas-only', action='store_true',
                    help='Only generate BLAS wrappers')
    ap.add_argument('--lapack-only', action='store_true',
                    help='Only generate LAPACK wrappers')
    ap.add_argument('--dump', action='store_true',
                    help='Dump generated code to stdout instead of files')
    args = ap.parse_args()

    suffix = '_64' if args.ilp64 else ''

    if not args.lapack_only:
        blas_src = os.path.join(BASE_DIR, 'fblas.pyf.src')
        print(f'Parsing {blas_src}...')
        blas_routines = parser_module.parse_pyf_file(blas_src)
        print(f'  -> {len(blas_routines)} BLAS routines')

        blas_pyx = generate_blas_pyx(blas_routines, ilp64=args.ilp64)

        if args.dump:
            print(blas_pyx)
        else:
            outfile = os.path.join(args.outdir, f'_pyblas{suffix}.pyx')
            os.makedirs(args.outdir, exist_ok=True)
            with open(outfile, 'w') as f:
                f.write(blas_pyx)
            print(f'Wrote {outfile}')

    if not args.blas_only:
        lapack_src = os.path.join(BASE_DIR, 'flapack.pyf.src')
        print(f'Parsing {lapack_src}...')
        lapack_routines = parser_module.parse_pyf_file(lapack_src)
        print(f'  -> {len(lapack_routines)} LAPACK routines')

        lapack_pyx = generate_lapack_pyx(lapack_routines, ilp64=args.ilp64)

        if args.dump:
            print(lapack_pyx)
        else:
            outfile = os.path.join(args.outdir, f'_pylapack{suffix}.pyx')
            os.makedirs(args.outdir, exist_ok=True)
            with open(outfile, 'w') as f:
                f.write(lapack_pyx)
            print(f'Wrote {outfile}')


if __name__ == '__main__':
    main()
