name: Cross-only compilation environment

concurrency:
  group: nonative-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - ci-cross

permissions:
  contents: read

jobs:
  cross_conda_aarch64:
    name: Cross x86-64 to aarch64
    if: "github.repository == 'rgommers/scipy' || github.repository == ''"
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: true
        use-only-tar-bz2: false
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        auto-activate-base: true
        activate-environment: ""

    # TODO: add caching for conda env (see macos_meson.yml)

    - name: Set up x86-64 build env (native)
      run: |
        mamba create -n build-env gxx_linux-aarch64 gfortran_linux-aarch64 python=3.11 meson-python build numpy pythran cython pkg-config

    - name: Set up aarch64 host env (cross)
      run: |
        CONDA_SUBDIR=linux-aarch64 mamba create -n host-env python numpy openblas libstdcxx-ng libgfortran-ng pybind11

    - name: Cross-compile SciPy
      run: |
        conda activate build-env
        # We're cross-compiling, so unset these environment variables that the
        # activate scripts define:
        unset CFLAGS
        unset CXXFLAGS
        unset FFLAGS
        unset LDFLAGS
        # NOTE: without this export, I see:
        # Determining dependency 'openblas' with pkg-config executable '/usr/share/miniconda3/envs/build-env/bin/pkg-config'
        # env[PKG_CONFIG_PATH]:
        # env[PKG_CONFIG_SYSROOT_DIR]: /usr/share/miniconda3/envs/host-env/
        # env[PKG_CONFIG_LIBDIR]: /usr/share/miniconda3/envs/host-env/lib/pkgconfig
        # Called `/usr/share/miniconda3/envs/build-env/bin/pkg-config --modversion openblas` -> 1
        # stderr:
        # Package openblas was not found in the pkg-config search path.
        # Perhaps you should add the directory containing `openblas.pc'
        # to the PKG_CONFIG_PATH environment variable
        # No package 'openblas' found
        # NOTE: the sys_root and pkg_config_libdir in the cross file (as per
        #       the Meson docs) are ineffective, both in CI and locally.
        #       In addition, using `sys_root` breaks including Python.h
        export PKG_CONFIG_PATH=/usr/share/miniconda3/envs/host-env/lib/pkgconfig

        # `-wnx` means: `--wheel --no-isolation --skip-dependency-check`
        python -m build -wnx -Cbuilddir=build -Csetup-args=--cross-file=$PWD/ci/cross_aarch64.ini

        # meson-python doesn't yet know about cross builds, so we get a wheel
        # with a `_x86_64` tag - fix that:
        mv dist/scipy-1.11.0.dev0-cp311-cp311-linux_x86_64.whl dist/scipy-1.11.0.dev0-cp311-cp311-linux_aarch64.whl

        # NOTE: Meson also gets the extensions of the individual extension
        # modules wrong and puts x86_64-linux-gnu.so in there. This needs
        # fixing, but has no consequences (the wheel should run fine on
        # aarch64).

    - name: (debug) echo meson-log.txt
      if: success() || failure()
      run: |
        cat build/meson-logs/meson-log.txt
