name: GPU jobs

on:
  push:
    branches:
      - maintenance/**
      - gpu-ci
  pull_request:
    branches:
      - main
      - maintenance/**

permissions:
   contents: read  # to fetch code (actions/checkout)

env:
  CCACHE_DIR: "${{ github.workspace }}/.ccache"
  PIXI_CACHE_DIR: "${{ github.workspace }}/.cache/rattler"
  XP_TESTS: >-
    -t scipy.cluster
    -t scipy.constants
    -t scipy.fft
    -t scipy.special.tests.test_logsumexp
    -t scipy.special.tests.test_support_alternative_backends
    -t scipy._lib.tests.test_array_api
    -t scipy._lib.tests.test__util
    -t scipy.differentiate.tests.test_differentiate
    -t scipy.integrate.tests.test_tanhsinh
    -t scipy.integrate.tests.test_cubature
    -t scipy.optimize.tests.test_bracket
    -t scipy.optimize.tests.test_chandrupatla
    -t scipy.optimize.tests.test_optimize
    -t scipy.stats
    -t scipy.ndimage
    -t scipy.integrate.tests.test_quadrature
    -t scipy.signal.tests.test_signaltools

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')

  pytorch_gpu:
    name: PyTorch GPU
    #needs: get_commit_message
    runs-on: ghcr.io/cirruslabs/ubuntu-runner-amd64-gpu:22.04
    steps:
      - name: Checkout scipy repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive

      - name: Cache pixi
        uses: cirruslabs/cache@caa3ad0624c6c2acd8ba50ad452d1f44bba078bb # v4
        with:
          path: ${{ env.PIXI_CACHE_DIR }}
          key: ${{ runner.os }}-gpu

      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          pixi-version: v0.39.2
          manifest-path: .github/workflows/pixi.toml
          #cache: true
          #cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build SciPy
        working-directory: .github/workflows
        run: pixi run build

      - name: Run array types tests
        working-directory: .github/workflows
        run: pixi run -e torch-cuda test-torch -v -s cluster  # TODO: use XP_TESTS env var
